package com.samokha.takeaway.employeeservice.domain;

import javax.persistence.*;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDate;
import java.util.UUID;

@Entity
public class Employee {

	/**
	 * UUID automatically randomly generated by hibernate's UUIDGenerationStrategy
	 * http://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#identifiers-generators-uuid
	 */
	@Id
	@GeneratedValue
	@org.hibernate.annotations.Type(type="uuid-char") //make uuid human-readable on DB level
	private UUID id;

	@Column(unique = true, length = 100, nullable = false)
	@Size(max = 100)
	@Email
	@NotNull
	@NotEmpty
	//TODO test email validation
	private String email;

	private String fullName;

	//TODO validate age?
	private LocalDate birthday;

	@ManyToOne
	private Department department;

	public Employee() {
	}

	public Employee(@Size(max = 100) @Email String email, String fullName, LocalDate birthday, Department department) {
		this.email = email;
		this.fullName = fullName;
		this.birthday = birthday;
		this.department = department;
	}

	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public LocalDate getBirthday() {
		return birthday;
	}

	public void setBirthday(LocalDate birthday) {
		this.birthday = birthday;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}
}
